### ISSUE TITLE
Crash when updating the RemoteSession

### ISSUE THREAD

**Issue by kelsos** [kelsos/mbrc#53]
On P7-L12 (hwp7) running Android 4.4

```java
java.lang.RuntimeException: Could not dispatch event: class com.kelsos.mbrc.events.ui.PlayStateChange to handler [EventHandler public void com.kelsos.mbrc.services.RemoteSessionManager.updateState(com.kelsos.mbrc.events.ui.PlayStateChange)]: null
at com.squareup.otto.Bus.throwRuntimeException(Bus.java:458)
at com.squareup.otto.Bus.dispatch(Bus.java:388)
at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
at com.squareup.otto.Bus.post(Bus.java:338)
at com.kelsos.mbrc.utilities.MainThreadBusWrapper.lambda$post$19(MainThreadBusWrapper.java:23)
at com.kelsos.mbrc.utilities.MainThreadBusWrapper.access$lambda$0(MainThreadBusWrapper.java)
at com.kelsos.mbrc.utilities.MainThreadBusWrapper$$Lambda$1.run(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5290)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at android.os.Parcel.readException(Parcel.java:1481)
at android.os.Parcel.readException(Parcel.java:1429)
at android.media.IAudioService$Stub$Proxy.registerMediaButtonIntent(IAudioService.java:1689)
at android.media.AudioManager.registerMediaButtonIntent(AudioManager.java:2223)
at android.media.AudioManager.registerMediaButtonEventReceiver(AudioManager.java:2208)
at android.support.v4.media.session.MediaSessionCompatApi18.registerMediaButtonEventReceiver(MediaSessionCompatApi18.java:35)
at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.update(MediaSessionCompat.java:1286)
at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setActive(MediaSessionCompat.java:1149)
at android.support.v4.media.session.MediaSessionCompat.setActive(MediaSessionCompat.java:240)
at com.kelsos.mbrc.services.RemoteSessionManager.updateState(RemoteSessionManager.java:132)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
at com.squareup.otto.Bus.dispatch(Bus.java:386)
... 14 more
```

**Comment by kelsos** [comment]
Should be fixed in the v0.11.2
